name: Terraform POC Destroy 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) OIDC login to AWS
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          aws-region:      ${{ secrets.AWS_REGION }}
          role-session-name: GitHubDestroy

      # 3) Terraform CLI
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.4.6 }

      # 4) Init with the same backend
      - name: Terraform Init (destroy)
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=poc/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      # 5) Terraform Destroy
      - name: Terraform Destroy
        env:
          TF_IN_AUTOMATION: true          # reduces prompts
          TF_CLI_ARGS: "-input=false"     # no interactive input
        run: terraform destroy -auto-approve
